title: Arda Ozkurt's Personal Website
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://www.hepsiburada.com/
  another_url: https://lichess.org/
  is_project_page : https://github.com/ardaozkurt
  
