title: Arda Ozkurt's Personal Website
description: Arda Ozkurt's Personal Website
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: http://example.com/download.zip
  another_url: another value
  is_project_page : https://github.com/ardaozkurt
  <a href="/AP_CS_A_Units.md" class="button">AP CS A Units</a>
  
